use crate::Packet;
use crate::parse_packet;
use std::slice;

pub struct PacketHandle<'a>(pub Packet<'a>);

/// Parses a packet from a raw C pointer.
///
/// # Safety
/// `data` must be a valid pointer to a contiguous block of memory of at least `len` bytes.
/// The caller must ensure the memory outlives the returned `PacketHandle`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn packet_parse(data: *const u8, len: usize) -> *mut PacketHandle<'static> {
    if data.is_null() || len == 0 {
        return std::ptr::null_mut();
    }

    let slice = unsafe { slice::from_raw_parts(data, len) };

    match parse_packet(slice) {
        Ok(packet) => {
            let handle = Box::new(PacketHandle(packet));

            unsafe {
                let handle_static: Box<PacketHandle<'static>> = std::mem::transmute(handle);
                Box::into_raw(handle_static)
            }
        }
        Err(_) => std::ptr::null_mut(),
    }
}

/// Frees the allocated PacketHandle.
///
/// # Safety
/// `handle` must be a valid pointer generated by `packet_parse`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn packet_free(handle: *mut PacketHandle<'static>) {
    if !handle.is_null() {
        let _ = unsafe { Box::from_raw(handle) };
    }
}

#[repr(C)]
pub struct ClassifyResult {
    pub is_valid: bool,
    pub protocol: u8,
    pub dest_port: u16,
    pub error_code: u32,
}

fn error_to_code(err: &crate::error::ParseError) -> u32 {
    match err {
        crate::error::ParseError::PacketTooShort => 1,
        crate::error::ParseError::InvalidEtherType => 2,
        crate::error::ParseError::InvalidIpv4Version => 3,
        crate::error::ParseError::InvalidIpv4HeaderLength => 4,
        crate::error::ParseError::InvalidIpv4TotalLength => 5,
        crate::error::ParseError::InvalidUdpLength => 6,
        crate::error::ParseError::UnsupportedProtocol => 7,
    }
}

/// Classifies a packet returning result by value, without heap allocations.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn packet_classify(
    data: *const u8,
    len: usize,
) -> ClassifyResult {
    if data.is_null() || len == 0 {
        return ClassifyResult {
            is_valid: false,
            protocol: 0,
            dest_port: 0,
            error_code: 1,
        };
    }

    let slice = unsafe { std::slice::from_raw_parts(data, len) };

    match crate::parse_packet(slice) {
        Ok(packet) => {
            if let Some(udp) = packet.udp {
                ClassifyResult {
                    is_valid: true,
                    protocol: 1,
                    dest_port: udp.destination_port,
                    error_code: 0,
                }
            } else {
                ClassifyResult {
                    is_valid: true,
                    protocol: 0,
                    dest_port: 0,
                    error_code: 0,
                }
            }
        }
        Err(e) => ClassifyResult {
            is_valid: false,
            protocol: 0,
            dest_port: 0,
            error_code: error_to_code(&e),
        }
    }
}